/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizza;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author fradd
 */
public class order extends javax.swing.JFrame {
    private double total=0.0;
    private int x=0;
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst2;
    Statement st;
    ResultSet rs;
        
    /**
     * Creates new form order
     */
    public order() {
        initComponents();
        init();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/pizza","root","");
            //first item
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM pizza WHERE pizzaid='1'");
            if(rs.next()){
                lbl_name1.setText(rs.getString(2));
                lbl_price1.setText(rs.getString(3));   
            }
            //secound item
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM pizza WHERE pizzaid='2'");
            if(rs.next()){
                lbl_name4.setText(rs.getString(2));
                lbl_price4.setText(rs.getString(3));
            }
            //third item
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM pizza WHERE pizzaid='3'");
            if(rs.next()){
                lbl_name8.setText(rs.getString(2));
                lbl_price8.setText(rs.getString(3));
            }
            //fourth item
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM pizza WHERE pizzaid='4'");
            if(rs.next()){
                lbl_name10.setText(rs.getString(2));
                lbl_price10.setText(rs.getString(3));
            }
            //fifth item
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM pizza WHERE pizzaid='5'");
            if(rs.next()){
                lbl_name2.setText(rs.getString(2));
                lbl_price2.setText(rs.getString(3));
            }
            //six item
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM pizza WHERE pizzaid='6'");
            if(rs.next()){
                lbl_name5.setText(rs.getString(2));
                lbl_price5.setText(rs.getString(3));
            }
            //seven item
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM pizza WHERE pizzaid='7'");
            if(rs.next()){
                lbl_name9.setText(rs.getString(2));
                lbl_price9.setText(rs.getString(3));
            }
            //eight item
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM pizza WHERE pizzaid='8'");
            if(rs.next()){
                lbl_name11.setText(rs.getString(2));
                lbl_price11.setText(rs.getString(3));
            }
            con.close();
        }
    catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
    }
    
    public void init() {
        setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void setTime(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                while(true){
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(order.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Date date=new Date();
                    SimpleDateFormat tf = new SimpleDateFormat("h:mm:ss aa");
                    SimpleDateFormat df = new SimpleDateFormat("EEEE, dd-MM-yyyy");
                    String time = tf.format(date);
                    jTxtTime.setText(time.split(" ")[0]+" "+time.split(" ")[1]);
                    jTxtDate.setText(df.format(date));
                }
            }
        }).start();
    }
    
    public void pizzashop(){
        jTextArea.setText("*****************************PizzaHut*******************************\n"
                +"Time: "+jTxtTime.getText()+" Date: "+jTxtDate.getText()+"\n"
        +"**********************************************************************"+"\n"
        +"Item Name:\t\t\t"+"Price($)\n");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtTime = new javax.swing.JLabel();
        jTxtDate = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_pic1 = new javax.swing.JLabel();
        btn_order1 = new javax.swing.JButton();
        cmb_se1 = new javax.swing.JComboBox<>();
        lbl_name1 = new javax.swing.JLabel();
        lbl_price1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_pic2 = new javax.swing.JLabel();
        btn_order2 = new javax.swing.JButton();
        cmb_se2 = new javax.swing.JComboBox<>();
        lbl_name2 = new javax.swing.JLabel();
        lbl_price2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_pic4 = new javax.swing.JLabel();
        btn_order4 = new javax.swing.JButton();
        cmb_se4 = new javax.swing.JComboBox<>();
        lbl_name4 = new javax.swing.JLabel();
        lbl_price4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_pic5 = new javax.swing.JLabel();
        btn_order5 = new javax.swing.JButton();
        cmb_se5 = new javax.swing.JComboBox<>();
        lbl_name5 = new javax.swing.JLabel();
        lbl_price5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_pic8 = new javax.swing.JLabel();
        btn_order8 = new javax.swing.JButton();
        cmb_se8 = new javax.swing.JComboBox<>();
        lbl_name8 = new javax.swing.JLabel();
        lbl_price8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbl_pic9 = new javax.swing.JLabel();
        btn_order9 = new javax.swing.JButton();
        cmb_se9 = new javax.swing.JComboBox<>();
        lbl_name9 = new javax.swing.JLabel();
        lbl_price9 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lbl_pic10 = new javax.swing.JLabel();
        btn_order10 = new javax.swing.JButton();
        cmb_se10 = new javax.swing.JComboBox<>();
        lbl_name10 = new javax.swing.JLabel();
        lbl_price10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lbl_pic11 = new javax.swing.JLabel();
        btn_order11 = new javax.swing.JButton();
        cmb_se11 = new javax.swing.JComboBox<>();
        lbl_name11 = new javax.swing.JLabel();
        lbl_price11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_tot = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fradd\\OneDrive\\Documents\\NetBeansProjects\\pizza\\resources\\pizzaa.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jTxtTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTxtTime.setForeground(new java.awt.Color(255, 255, 255));

        jTxtDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTxtDate.setForeground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jTxtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtTime)
                            .addComponent(jTxtDate)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbl_pic1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fradd\\OneDrive\\Documents\\NetBeansProjects\\pizza\\resources\\p1.jpg")); // NOI18N

        btn_order1.setBackground(new java.awt.Color(76, 111, 0));
        btn_order1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_order1.setForeground(new java.awt.Color(255, 255, 255));
        btn_order1.setText("Add");
        btn_order1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_order1ActionPerformed(evt);
            }
        });

        cmb_se1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "Small", "Medium", "Large" }));

        lbl_name1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_name1.setText("Masala Magic");

        lbl_price1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_price1.setText("500");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Rs");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_pic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_se1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_order1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lbl_name1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_price1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name1)
                    .addComponent(lbl_price1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_se1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_order1)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbl_pic2.setIcon(new javax.swing.ImageIcon("C:\\Users\\fradd\\OneDrive\\Documents\\NetBeansProjects\\pizza\\resources\\p5.jpg")); // NOI18N

        btn_order2.setBackground(new java.awt.Color(76, 111, 0));
        btn_order2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_order2.setForeground(new java.awt.Color(255, 255, 255));
        btn_order2.setText("Add");
        btn_order2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_order2ActionPerformed(evt);
            }
        });

        cmb_se2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "Small", "Medium", "Large" }));

        lbl_name2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_name2.setText("Veggie Supreme");

        lbl_price2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_price2.setText("800");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Rs");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_pic2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(lbl_name2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_price2))
            .addComponent(btn_order2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(cmb_se2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name2)
                    .addComponent(lbl_price2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_se2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_order2)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        lbl_pic4.setIcon(new javax.swing.ImageIcon("C:\\Users\\fradd\\OneDrive\\Documents\\NetBeansProjects\\pizza\\resources\\p2.jpg")); // NOI18N

        btn_order4.setBackground(new java.awt.Color(76, 111, 0));
        btn_order4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_order4.setForeground(new java.awt.Color(255, 255, 255));
        btn_order4.setText("Add");
        btn_order4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_order4ActionPerformed(evt);
            }
        });

        cmb_se4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "Small", "Medium", "Large" }));

        lbl_name4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_name4.setText("Tandoori Chicken");

        lbl_price4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_price4.setText("600");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Rs");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_pic4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_se4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_order4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lbl_name4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_price4))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pic4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name4)
                    .addComponent(lbl_price4)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_se4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_order4)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lbl_pic5.setIcon(new javax.swing.ImageIcon("C:\\Users\\fradd\\OneDrive\\Documents\\NetBeansProjects\\pizza\\resources\\p6.jpg")); // NOI18N

        btn_order5.setBackground(new java.awt.Color(76, 111, 0));
        btn_order5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_order5.setForeground(new java.awt.Color(255, 255, 255));
        btn_order5.setText("Add");
        btn_order5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_order5ActionPerformed(evt);
            }
        });

        cmb_se5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "Small", "Medium", "Large" }));

        lbl_name5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_name5.setText("Super Supreme");

        lbl_price5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_price5.setText("900");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Rs");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_pic5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_order5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_se5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lbl_name5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_price5))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pic5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name5)
                    .addComponent(lbl_price5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_se5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_order5)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        lbl_pic8.setIcon(new javax.swing.ImageIcon("C:\\Users\\fradd\\OneDrive\\Documents\\NetBeansProjects\\pizza\\resources\\p3.jpg")); // NOI18N

        btn_order8.setBackground(new java.awt.Color(76, 111, 0));
        btn_order8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_order8.setForeground(new java.awt.Color(255, 255, 255));
        btn_order8.setText("Add");
        btn_order8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_order8ActionPerformed(evt);
            }
        });

        cmb_se8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "Small", "Medium", "Large" }));

        lbl_name8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_name8.setText("Black Chicken ");

        lbl_price8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_price8.setText("750");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Rs");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_pic8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(lbl_name8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_price8))
            .addComponent(btn_order8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(cmb_se8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pic8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name8)
                    .addComponent(lbl_price8)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_se8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_order8)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        lbl_pic9.setIcon(new javax.swing.ImageIcon("C:\\Users\\fradd\\OneDrive\\Documents\\NetBeansProjects\\pizza\\resources\\p7.jpg")); // NOI18N

        btn_order9.setBackground(new java.awt.Color(76, 111, 0));
        btn_order9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_order9.setForeground(new java.awt.Color(255, 255, 255));
        btn_order9.setText("Add");
        btn_order9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_order9ActionPerformed(evt);
            }
        });

        cmb_se9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "Small", "Medium", "Large" }));

        lbl_name9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_name9.setText("Spicy Seafood ");

        lbl_price9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_price9.setText("1000");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Rs");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_pic9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(lbl_name9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_price9))
            .addComponent(btn_order9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(cmb_se9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pic9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name9)
                    .addComponent(lbl_price9)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_se9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_order9)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        lbl_pic10.setIcon(new javax.swing.ImageIcon("C:\\Users\\fradd\\OneDrive\\Documents\\NetBeansProjects\\pizza\\resources\\p4.jpg")); // NOI18N

        btn_order10.setBackground(new java.awt.Color(76, 111, 0));
        btn_order10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_order10.setForeground(new java.awt.Color(255, 255, 255));
        btn_order10.setText("Add");
        btn_order10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_order10ActionPerformed(evt);
            }
        });

        cmb_se10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "Small", "Medium", "Large" }));

        lbl_name10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_name10.setText("BBQ Chicken");

        lbl_price10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_price10.setText("820");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Rs");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_pic10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(lbl_name10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_price10))
            .addComponent(btn_order10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(cmb_se10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pic10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name10)
                    .addComponent(lbl_price10)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_se10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_order10)
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        lbl_pic11.setIcon(new javax.swing.ImageIcon("C:\\Users\\fradd\\OneDrive\\Documents\\NetBeansProjects\\pizza\\resources\\p8.jpg")); // NOI18N

        btn_order11.setBackground(new java.awt.Color(76, 111, 0));
        btn_order11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_order11.setForeground(new java.awt.Color(255, 255, 255));
        btn_order11.setText("Add");
        btn_order11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_order11ActionPerformed(evt);
            }
        });

        cmb_se11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "Small", "Medium", "Large" }));

        lbl_name11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_name11.setText("Christmas Pizza ");

        lbl_price11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_price11.setText("1200");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Rs");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_pic11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addComponent(lbl_name11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_price11))
            .addComponent(btn_order11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addComponent(cmb_se11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pic11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name11)
                    .addComponent(lbl_price11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_se11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_order11)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(76, 111, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Your Bill");

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel2)
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Total Price :-");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Rs");

        lbl_tot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btn_reset.setBackground(new java.awt.Color(255, 0, 51));
        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_reset.setText("Clear All");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_print.setBackground(new java.awt.Color(51, 255, 51));
        btn_print.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_print.setText("Print Recipt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_tot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_print)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_reset)
                        .addGap(50, 50, 50)))
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(lbl_tot)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_order1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_order1ActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(lbl_price1.getText());
        int Type = cmb_se1.getSelectedIndex();   //get item from combobox
        if (Type==0){
            JOptionPane.showMessageDialog(null, "Please select pizza type");
        }else{
            if(Type==1){
                price = price;
            }
            else if (Type==2){
                price=price+200;
            }
            else if (Type==3){
                price= price+500;
            }
        x++;
        if (x==1){
        pizzashop();
        }
        
        jTextArea.setText(jTextArea.getText()+x+". "+lbl_name1.getText()+"t\t\t"+price+"\n");
        total=total+price;
        lbl_tot.setText(Double.toString(total));
        cmb_se1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btn_order1ActionPerformed

    private void btn_order4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_order4ActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(lbl_price4.getText());
        int Type = cmb_se4.getSelectedIndex();   //get item from combobox
        if (Type==0){
            JOptionPane.showMessageDialog(null, "Please select pizza type");
        }else{
            if(Type==1){
                price = price;
            }
            else if (Type==2){
                price=price+200;
            }
            else if (Type==3){
                price= price+500;
            }
        x++;
        if (x==1){
        pizzashop();
        }
        
        jTextArea.setText(jTextArea.getText()+x+". "+lbl_name4.getText()+"t\t\t"+price+"\n");
        total=total+price;
        lbl_tot.setText(Double.toString(total));
        cmb_se4.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btn_order4ActionPerformed

    private void btn_order8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_order8ActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(lbl_price8.getText());
        int Type = cmb_se8.getSelectedIndex();   //get item from combobox
        if (Type==0){
            JOptionPane.showMessageDialog(null, "Please select pizza type");
        }else{
            if(Type==1){
                price = price;
            }
            else if (Type==2){
                price=price+200;
            }
            else if (Type==3){
                price= price+500;
            }
        x++;
        if (x==1){
        pizzashop();
        }
        
        jTextArea.setText(jTextArea.getText()+x+". "+lbl_name8.getText()+"t\t\t"+price+"\n");
        total=total+price;
        lbl_tot.setText(Double.toString(total));
        cmb_se8.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btn_order8ActionPerformed

    private void btn_order10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_order10ActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(lbl_price10.getText());
        int Type = cmb_se10.getSelectedIndex();   //get item from combobox
        if (Type==0){
            JOptionPane.showMessageDialog(null, "Please select pizza type");
        }else{
            if(Type==1){
                price = price;
            }
            else if (Type==2){
                price=price+200;
            }
            else if (Type==3){
                price= price+500;
            }
        x++;
        if (x==1){
        pizzashop();
        }
        
        jTextArea.setText(jTextArea.getText()+x+". "+lbl_name10.getText()+"t\t\t"+price+"\n");
        total=total+price;
        lbl_tot.setText(Double.toString(total));
        cmb_se10.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btn_order10ActionPerformed

    private void btn_order2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_order2ActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(lbl_price2.getText());
        int Type = cmb_se2.getSelectedIndex();   //get item from combobox
        if (Type==0){
            JOptionPane.showMessageDialog(null, "Please select pizza type");
        }else{
            if(Type==1){
                price = price;
            }
            else if (Type==2){
                price=price+200;
            }
            else if (Type==3){
                price= price+500;
            }
        x++;
        if (x==1){
        pizzashop();
        }
        
        jTextArea.setText(jTextArea.getText()+x+". "+lbl_name2.getText()+"t\t\t"+price+"\n");
        total=total+price;
        lbl_tot.setText(Double.toString(total));
        cmb_se2.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btn_order2ActionPerformed

    private void btn_order5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_order5ActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(lbl_price5.getText());
        int Type = cmb_se5.getSelectedIndex();   //get item from combobox
        if (Type==0){
            JOptionPane.showMessageDialog(null, "Please select pizza type");
        }else{
            if(Type==1){
                price = price;
            }
            else if (Type==2){
                price=price+200;
            }
            else if (Type==3){
                price= price+500;
            }
        x++;
        if (x==1){
        pizzashop();
        }
        
        jTextArea.setText(jTextArea.getText()+x+". "+lbl_name5.getText()+"t\t\t"+price+"\n");
        total=total+price;
        lbl_tot.setText(Double.toString(total));
        cmb_se5.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btn_order5ActionPerformed

    private void btn_order9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_order9ActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(lbl_price9.getText());
        int Type = cmb_se9.getSelectedIndex();   //get item from combobox
        if (Type==0){
            JOptionPane.showMessageDialog(null, "Please select pizza type");
        }else{
            if(Type==1){
                price = price;
            }
            else if (Type==2){
                price=price+200;
            }
            else if (Type==3){
                price= price+500;
            }
        x++;
        if (x==1){
        pizzashop();
        }
        
        jTextArea.setText(jTextArea.getText()+x+". "+lbl_name9.getText()+"t\t\t"+price+"\n");
        total=total+price;
        lbl_tot.setText(Double.toString(total));
        cmb_se9.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btn_order9ActionPerformed

    private void btn_order11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_order11ActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(lbl_price11.getText());
        int Type = cmb_se11.getSelectedIndex();   //get item from combobox
        if (Type==0){
            JOptionPane.showMessageDialog(null, "Please select pizza type");
        }else{
            if(Type==1){
                price = price;
            }
            else if (Type==2){
                price=price+200;
            }
            else if (Type==3){
                price= price+500;
            }
        x++;
        if (x==1){
        pizzashop();
        }
        
        jTextArea.setText(jTextArea.getText()+x+". "+lbl_name11.getText()+"t\t\t"+price+"\n");
        total=total+price;
        lbl_tot.setText(Double.toString(total));
        cmb_se11.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btn_order11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(total==0){
            JOptionPane.showMessageDialog(null, "Order List Empty");
        }else{
            jTextArea.setText(jTextArea.getText()
            +"\n**********************************************************************\n"
            +"Total: \t\t\t"+(total)+"\n\n"
            +"****************************Thank You******************************\n");
        };
        jButton1.setEnabled(false);
        btn_order1.setEnabled(false);
        btn_order2.setEnabled(false);
        btn_order11.setEnabled(false);
        btn_order4.setEnabled(false);
        btn_order5.setEnabled(false);
        btn_order10.setEnabled(false);
        btn_order9.setEnabled(false);
        btn_order8.setEnabled(false);
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/pizza","root","");
            
            String dis =jTextArea.getText();
            String query = "insert into temp_invoice (disc) values (?) ";
            pst = con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, dis);
            pst.executeUpdate();
                    
            String time=jTxtTime.getText();
            String date=jTxtDate.getText();
            
            String query2 = "insert into invoice (datee,timee,price,dis) values (?,?,?,?) ";
            pst2 = con.prepareStatement(query2,Statement.RETURN_GENERATED_KEYS);
            pst2.setString(1, date);
            pst2.setString(2, time);
            pst2.setString(3, Double.toString(total));
            pst2.setString(4, dis);
            pst2.executeUpdate();
            con.close();
            
            JOptionPane.showMessageDialog(null, "sucessfull orderd");
        }
        catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(true);
        total=0.0;
        x=0;
        jTextArea.setText("");
        lbl_tot.setText("");
        btn_order1.setEnabled(true);
        btn_order2.setEnabled(true);
        btn_order11.setEnabled(true);
        btn_order4.setEnabled(true);
        btn_order5.setEnabled(true);
        btn_order10.setEnabled(true);
        btn_order9.setEnabled(true);
        btn_order8.setEnabled(true);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_order1;
    private javax.swing.JButton btn_order10;
    private javax.swing.JButton btn_order11;
    private javax.swing.JButton btn_order2;
    private javax.swing.JButton btn_order4;
    private javax.swing.JButton btn_order5;
    private javax.swing.JButton btn_order8;
    private javax.swing.JButton btn_order9;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_reset;
    private javax.swing.JComboBox<String> cmb_se1;
    private javax.swing.JComboBox<String> cmb_se10;
    private javax.swing.JComboBox<String> cmb_se11;
    private javax.swing.JComboBox<String> cmb_se2;
    private javax.swing.JComboBox<String> cmb_se4;
    private javax.swing.JComboBox<String> cmb_se5;
    private javax.swing.JComboBox<String> cmb_se8;
    private javax.swing.JComboBox<String> cmb_se9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JLabel jTxtDate;
    private javax.swing.JLabel jTxtTime;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_name10;
    private javax.swing.JLabel lbl_name11;
    private javax.swing.JLabel lbl_name2;
    private javax.swing.JLabel lbl_name4;
    private javax.swing.JLabel lbl_name5;
    private javax.swing.JLabel lbl_name8;
    private javax.swing.JLabel lbl_name9;
    private javax.swing.JLabel lbl_pic1;
    private javax.swing.JLabel lbl_pic10;
    private javax.swing.JLabel lbl_pic11;
    private javax.swing.JLabel lbl_pic2;
    private javax.swing.JLabel lbl_pic4;
    private javax.swing.JLabel lbl_pic5;
    private javax.swing.JLabel lbl_pic8;
    private javax.swing.JLabel lbl_pic9;
    private javax.swing.JLabel lbl_price1;
    private javax.swing.JLabel lbl_price10;
    private javax.swing.JLabel lbl_price11;
    private javax.swing.JLabel lbl_price2;
    private javax.swing.JLabel lbl_price4;
    private javax.swing.JLabel lbl_price5;
    private javax.swing.JLabel lbl_price8;
    private javax.swing.JLabel lbl_price9;
    private javax.swing.JLabel lbl_tot;
    // End of variables declaration//GEN-END:variables
}
